apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-db-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: wp-db-efs-pv
