apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress
data:
  DB_NAME: "wordpress"
  DB_USER: "wpuser"
  DB_HOST: "wp-db"
  WP_URL: "http://localhost:8080"
  WP_TITLE: "WordPressEKS"
  WP_ADMIN_USER: "admin"
  WP_ADMIN_EMAIL: "kevin.aceves@hotmail.com"
