apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: wordpress
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk # rootpassword
  MYSQL_PASSWORD: d3BwYXNzd29yZA== # wppassword
  WP_ADMIN_PASSWORD: YWRtaW5wYXNzd29yZA== # adminpassword
