Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "private_network", ip: "192.168.33.10"
  

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
    end

    config.vm.provision "file", source: "./mongoInstall.sh", destination: "/tmp/mongoInstall.sh"
    config.vm.provision "file", source: "./config.ini", destination: "/tmp/config.ini"
    config.vm.provision "shell", inline: <<-SHELL
        chmod +x /tmp/mongoInstall.sh
    SHELL
end