
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    
    config.vm.network "private_network", ip: "192.168.250.44"
    # Reenvía el puerto 80 de la VM al puerto 8080 del host 
    config.vm.network "forwarded_port", guest: 80, host: 8080

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end

    # Haremos el aprovisionamiento con ansible_local (sobre nuestra maquina)
    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "provisioning/playbook.yml"
    end
end
